spring.datasource.url=jdbc:mysql://localhost:3306/digital_twin
spring.datasource.username=root
spring.datasource.password=@Sraavya2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=8080